sudo: required
language: python
python:
          - "3.7"
services:
          - docker
          
cache: pip
install: "pip install -r requirements.txt"
script: 
        - coverage run test.py
        - docker image build -t anthony77/assignment2 .
codecov:
  token: 58367684-1ee4-404d-9f86-dadd0ac7fd14
after_success:  
        - bash <(curl -s https://codecov.io/bash)
        #log in to docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #take built images and push to DOcker hub
        - docker push anthony77/assignment2
        #test
        
        
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Assignment2"
  env: "Assignment2-env"
  bucket_name: "elasticbeanstalk-us-east-1-127998730592"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  
  
        
        
        
