language: python
python:
          - "3.7"
cache: pip
install: "pip install -r requirements.txt"
script: coverage run test.py
after_success:  
        - export CODECOV_TOKEN="token"
        - bash <(curl -s https://codecov.io/bash)
        
