language: python
python:
          - "3.7"
cache: pip
install: "pip install -r requirements.txt"
script: coverage run test.py
codecov:
  token: c3f276c2-798d-44ef-adce-c92dfb517280
after_success:  
        - bash <(curl -s https://codecov.io/bash)
        
        
