language: python
python:
          - "3.7"
services:
          - docker
          
cache: pip
install: "pip install -r requirements.txt"
script: 
        - coverage run test.py
        - docker image build -t html-server-image:v1 .
codecov:
  token: c3f276c2-798d-44ef-adce-c92dfb517280
after_success:  
        #log in to docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #take built images and push to DOcker hub
        - docker push anthony77/assignment2
        #test
        
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Assignment2-Ver3"
  env: "Assignment2ver3-env"
  bucket_name: "elasticbeanstalk-us-west-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
        
        
        
